# Generated by Django 5.2.4 on 2025-08-05 08:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the fundraising campaign.', max_length=200)),
                ('description', models.TextField(help_text="A detailed description of the campaign's purpose.")),
                ('goal_amount', models.DecimalField(decimal_places=2, help_text='The target fundraising amount in your currency (e.g., USD).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='The total amount raised so far.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the campaign was created.')),
                ('end_date', models.DateField(help_text='The date the campaign is scheduled to end.')),
                ('is_active', models.BooleanField(default=True, help_text='Is the campaign currently accepting donations?')),
                ('creator', models.ForeignKey(help_text='The user who created this campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the donation.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('transaction_id', models.CharField(blank=True, help_text='The transaction ID from the payment gateway.', max_length=255, null=True, unique=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the donation was made.')),
                ('campaign', models.ForeignKey(help_text='The campaign this donation is for.', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.campaign')),
                ('donor', models.ForeignKey(blank=True, help_text='The user who made the donation. Can be empty for anonymous donations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-donated_at'],
            },
        ),
    ]
