# Generated by Django 6.1 on 2026-08-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('medical', 'Medical'), ('education', 'Education'), ('animals', 'Animals'), ('environment', 'Environment'), ('community', 'Community'), ('sports', 'Sports'), ('arts', 'Arts')], default='community', help_text='The cause category this campaign belongs to.', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier, auto-generated from the title if left blank.', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, help_text='An optional message from the donor.'),
        ),
    ]
