# Generated by Django 6.1 on 2026-08-29 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campaign_updated_at_alter_campaign_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional upload; falls back to the generated gradient cover art.', null=True, upload_to='covers/'),
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short headline for the update.', max_length=200)),
                ('body', models.TextField(help_text='The full text of the update.')),
                ('image', models.ImageField(blank=True, help_text='Optional image to accompany the update.', null=True, upload_to='updates/')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this update to the top of the campaign timeline.')),
                ('campaign', models.ForeignKey(help_text='The campaign this update belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Update',
                'verbose_name_plural': 'Campaign Updates',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
