# Generated by Django 6.1 on 2026-08-29 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_cover_image_campaignupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When the token stops being valid.')),
                ('user', models.OneToOneField(help_text='The user this verification token belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, help_text='Name to show instead of the username.', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A short bio shown on the profile.')),
                ('avatar', models.ImageField(blank=True, help_text='Optional profile picture.', null=True, upload_to='avatars/')),
                ('timezone', models.CharField(default='UTC', help_text="The user's timezone.", max_length=64)),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the email address has been verified.')),
                ('receives_email_updates', models.BooleanField(default=True, help_text='Opt in to email updates for saved campaigns.')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='SavedCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(help_text='The saved campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.campaign')),
                ('user', models.ForeignKey(help_text='The user who saved this campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Campaign',
                'verbose_name_plural': 'Saved Campaigns',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'campaign'), name='unique_user_campaign_save')],
            },
        ),
    ]
