# Generated by Django 6.1 on 2026-08-29 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailverificationtoken_profile_savedcampaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='expiring_notified',
            field=models.BooleanField(default=False, help_text='Whether the expiring-soon notification has already been sent.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='funded_notified',
            field=models.BooleanField(default=False, help_text='Whether the funded notification has already been sent.'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('update_posted', 'Update posted'), ('campaign_funded', 'Campaign funded'), ('expiring_soon', 'Expiring soon')], help_text='The type of notification.', max_length=20)),
                ('message', models.CharField(help_text='Human-readable notification text.', max_length=300)),
                ('read', models.BooleanField(default=False, help_text='Whether the user has read it.')),
                ('campaign', models.ForeignKey(blank=True, help_text='The related campaign, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.campaign')),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, help_text='The related campaign update, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.campaignupdate')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
