# Generated by Django 6.1 on 2026-08-29 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_campaign_expiring_notified_campaign_funded_notified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donated_at'], name='donation_donated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign', 'donated_at'], name='donation_camp_donated_idx'),
        ),
    ]
